// LEGAL VARIABLE
/*
let userName;        ✅
let $price;          ✅
let _value;          ✅
let user1;           ✅
let userAlert;       ✅
let myVar;           ✅
let firstName;       ✅ (camelCase)
*/

// ILLEGAL
/*
let "name";          ❌
let 1user;           ❌
let user name;       ❌
let var;             ❌
let @total;          ❌
*/

// 🐪 What is camelCase?
// camelCase = Name starts with small letter. Each new word begins with a capital letter.
/*
✔ Examples:
let userName;        ✅
let fullName;        ✅
let totalAmount;     ✅
*/